### ISSUE TITLE
Favicon shows double the unread emails

### ISSUE THREAD

**Issue by moradin** [mihai-chezan/owa_notifications_firefox_extension#30] opened 2019-10-03 14:22 UTC
Since the last update (2 Oct) the favicon shows twice as many unread emails as I have.

**Comment by mihai-chezan** [comment] 2019-10-03 16:42
Hi,

Could you tell me what OWA are you using.
Also, could you post a screenshot of it?

**Comment by moradin** [comment] 2019-10-03 16:54
I'm not sure if I understand the question correctly. I'm using outlook.office.com.
I can't really post a screenshot as the emails themselves are confidential.

**Comment by mihai-chezan** [comment] 2019-10-03 18:19
You are most probably affected because of this 

https://github.com/mihai-chezan/owa_notifications_firefox_extension/issues/29

**Comment by mihai-chezan** [comment] 2019-10-03 18:19
You are most probably affected because of this:

https://github.com/mihai-chezan/owa_notifications_firefox_extension/issues/29

Question: were the notifications working before for you?
Is the number of unread emails double because the `unread` emails show up in your Favourites virtual folder but also in the `regular` folder?

**Comment by mihai-chezan** [comment] 2019-10-03 18:26
@nerijusk
@AndSab

Do you have any issues with the new release?

**Comment by moradin** [comment] 2019-10-03 19:40
I don't use the notifications, only the favicon so I don't know if those worked. It is possible that the Favorites folder is the culprit here but this is definitely not how it worked before. Is there any way I could work around this?

**Comment by AndSab** [comment] 2019-10-04 06:04
> @nerijusk
> @AndSab
> 
> Do you have any issues with the new release?

I noticed double count for messages that are in received in Groups. As I don't really care about the count just about notification and indicator that something there I ignored them for the time being.

Now I checked why that count is multiplied and looks like MS is rendering two counts and hiding one of them:

```
<span class="_3Jn_7Iv4SwMTMOPJiydZLa _2c72q1kv-OOl7ERSzHFmKl">
  <span class="nSex22jJhxuH_NoJLuWL4">1
    <span class="screenReaderOnly">unread</span>
  </span>
</span>
<span class="_2jHPPTsq-QokR0fW2y0KI-">
  <span class="nSex22jJhxuH_NoJLuWL4">1
    <span class="screenReaderOnly">unread</span>
  </span>
</span>
```


`_2jHPPTsq-QokR0fW2y0KI-` has display:none and background-color: transparent

As I don't use favourites I didn't see any other cases of duplicate messages. I tried it now and double messages are displayed in the favicon. But this makes sense as folders are now duplicated in view.

**Comment by mihai-chezan** [comment] 2019-10-04 06:36
@AndSab That's valuable information and I think I can provide a fix for this regression by only counting visible elements.

It is also surprising that from what @moradin says, it seems that for him the addon worked before so he had not being affected by #29 

@moradin Did you set/had custom css selectors for unread emails (in the addon preferences)?

**Comment by moradin** [comment] 2019-10-04 07:40
No I didn't, but I was on vacation for like 2 weeks at the end of September so maybe that's why? Not sure what the time periods are that we are talking about.

**Comment by nerijusk** [comment] 2019-10-04 12:57
as @AndSab mentioned i see double count for groups too. otherwise it is correct.

**Comment by mihai-chezan** [comment] 2019-10-04 23:33
Released 1.9.7 which will not count invisible elements.
Still, if you have both Favorites and Normal folder, you will get duplicates.

**Comment by mihai-chezan** [comment] 2019-10-09 05:10
@moradin did the new release fix your issue?

**Comment by moradin** [comment] 2019-10-09 08:36
It fixed the issue if I close the Favorites part, if that's open then I still get everything counted twice.

**Comment by mihai-chezan** [comment] 2019-10-11 06:04
> It fixed the issue if I close the Favorites part, if that's open then I still get everything counted twice.

That is expected. I can only try to fix that if I get more help from you or somebody else that uses Office365 owa since I don't have access to it.
So what I need from you is:
1. Right click on "Favorites" folder and select "Inspect element" option
2. A panel will open up with the html of the current page and the element containing "Favorites" emails will be selected. You then right click on it and select "Copy->Outer HTML." and then reply here and paste the copied html.
You can take a look at #29 to get an idea how this was fixed with the help of @AndSab

**Comment by moradin** [comment] 2019-10-11 08:06
I have to add that this doesn't really bother me but I'm happy to help fix this.

Right clicking is captured by the page so it didn't work that way. I opened the Inspector, highlighted the div containing the favorites and copied the outer HTML. I hope this helps

`<div style="padding-left: 0px; padding-right: 28px;" class="_21GIf9eXgdq_YZiQrKnLYC yM6ioiXgtQ4G9DIFvnHHU" data-is-focusable="true" title="Favorites" role="treeitem" aria-expanded="true" aria-level="1" tabindex="0"><button type="button" data-is-focusable="false" tabindex="-1" class="ms-Button ms-Button--icon _3ro6VpUsGKbJLq-qGxzhp0 _3LRqJ7WzGdVvVSMUXfxeK- root-58" role="button" aria-hidden="true"><div class="ms-Button-flexContainer flexContainer-42"><i data-icon-name="ChevronDownMed" role="presentation" aria-hidden="true" class="ms-Button-icon _1IolX_6rKX93IRLO1O_oCP _1OPSsVxfk_GWTnwo-KIMYX flipForRtl icon-50"></i></div></button><span class="_16aPYHYIOVxzNYTA4BGnwS _3FwRpWCSns-2PgbiDhEErG">Favorites</span></div>`

**Comment by mihai-chezan** [comment] 2019-10-15 06:04
Thank you @moradin .
Unfortunately there is not information there for me to exclude the Favorites.
I need somehow the pasted html to contain the Favorite element (as above) but also the unread count element.

**Comment by moradin** [comment] 2019-10-15 12:08
ok, here's the whole favorites tree:

`<div class="_1ci7WbFYZSInPwqVpr89mC" role="tree"><div style="padding-left: 0px; padding-right: 28px;" class="_21GIf9eXgdq_YZiQrKnLYC yM6ioiXgtQ4G9DIFvnHHU" data-is-focusable="true" title="Favorites" role="treeitem" aria-expanded="true" aria-level="1" tabindex="0"><button type="button" data-is-focusable="false" tabindex="-1" class="ms-Button ms-Button--icon _3ro6VpUsGKbJLq-qGxzhp0 _3LRqJ7WzGdVvVSMUXfxeK- root-59" role="button" aria-hidden="true"><span class="ms-Button-flexContainer flexContainer-45" data-automationid="splitbuttonprimary"><i data-icon-name="ChevronDownMed" aria-hidden="true" class="ms-Button-icon _1IolX_6rKX93IRLO1O_oCP _1OPSsVxfk_GWTnwo-KIMYX flipForRtl icon-61"></i></span></button><span class="_16aPYHYIOVxzNYTA4BGnwS _3FwRpWCSns-2PgbiDhEErG">Favorites</span></div><div draggable="true"><div style="padding-left: 0px; padding-right: 28px;" class="_21GIf9eXgdq_YZiQrKnLYC qDw7SZ9r6S7r0_qZS1aIG" data-is-focusable="true" title="Inbox" role="treeitem" aria-selected="false" aria-level="2"><i data-icon-name="Inbox" aria-hidden="true" class="_1IolX_6rKX93IRLO1O_oCP qI0miNbM8RNNeR4_SQSa7 _1OPSsVxfk_GWTnwo-KIMYX root-62"></i><span class="_16aPYHYIOVxzNYTA4BGnwS _3FwRpWCSns-2PgbiDhEErG">Inbox</span><span class="_3Jn_7Iv4SwMTMOPJiydZLa"><span class="VvaKbiG13j8JUB9fmPlUP _3znt5bn-HsoKLR4JiGNhgk">3<span class="screenReaderOnly">unread</span></span></span></div></div><div draggable="true"><div style="padding-left: 0px; padding-right: 28px;" class="_21GIf9eXgdq_YZiQrKnLYC qDw7SZ9r6S7r0_qZS1aIG" data-is-focusable="true" title="Sent Items" role="treeitem" aria-selected="false" aria-level="2"><i data-icon-name="Send" aria-hidden="true" class="_1IolX_6rKX93IRLO1O_oCP qI0miNbM8RNNeR4_SQSa7 _1OPSsVxfk_GWTnwo-KIMYX root-62"></i><span class="_16aPYHYIOVxzNYTA4BGnwS _3FwRpWCSns-2PgbiDhEErG">Sent Items</span><span class="_3Jn_7Iv4SwMTMOPJiydZLa"></span></div></div><div draggable="true"><div style="padding-left: 0px; padding-right: 28px;" class="_21GIf9eXgdq_YZiQrKnLYC qDw7SZ9r6S7r0_qZS1aIG" data-is-focusable="true" title="Drafts" role="treeitem" aria-selected="false" aria-level="2"><i data-icon-name="Edit" aria-hidden="true" class="_1IolX_6rKX93IRLO1O_oCP qI0miNbM8RNNeR4_SQSa7 _1OPSsVxfk_GWTnwo-KIMYX root-62"></i><span class="_16aPYHYIOVxzNYTA4BGnwS _3FwRpWCSns-2PgbiDhEErG">Drafts</span><span class="_3Jn_7Iv4SwMTMOPJiydZLa"><span class="VvaKbiG13j8JUB9fmPlUP">2<span class="screenReaderOnly">items</span></span></span></div></div><div style="padding-left: 0px; padding-right: 28px;" class="_21GIf9eXgdq_YZiQrKnLYC qDw7SZ9r6S7r0_qZS1aIG _1pmm4dIxwC-S_TNlNCQ5Ys" data-is-focusable="true" title="Add favorite" role="treeitem" aria-level="2"><i aria-hidden="true" class="_1IolX_6rKX93IRLO1O_oCP visibilityHidden _1OPSsVxfk_GWTnwo-KIMYX root-63"></i><span class="_16aPYHYIOVxzNYTA4BGnwS _3FwRpWCSns-2PgbiDhEErG">Add favorite</span></div><span class="screenReaderOnly" aria-live="assertive" aria-atomic="true"></span></div>`

You can see the unread count (3) and the favorites div. Is this enough?

**Comment by mihai-chezan** [comment] 2019-10-15 20:30
Yes, this should be enough.
When I get a bit of time, I'll try to see how to change the code such that the Favorites is ignored.
Thank you for your help.

**Comment by mihai-chezan** [comment] 2019-10-18 16:54
I gave it a bit more thought and I think I will leave it as is.
If I implement the excluding of Favorites then maybe some users will complain that they actually use Favorites (and not use the other folders and they just add the folders they are interested in to the favorites).
Considering the fact that if you collapse Favorites it does not count Favorites anymore, or if you collapse the other folders, they are not counted, I think is good enough.

But thank you @moradin for your help to try to solve this.

**Closed as completed by mihai-chezan** 2019-10-18 16:54 UTC
Labels: bug

**Comment by tacrita0** [comment] 2019-10-29 11:51
Hi, on https://outlook.office.com/mail/inbox if I select "Auto" on "Css Selector for unread emails detections"  the favicon shows twice as many unread emails as I have. If I select any other settings, the unread emails are not visible, only a colored dot is visible on the firefox tab when a new email arrives. Is there any way to fix it?

**Comment by mihai-chezan** [comment] 2019-10-29 18:25
@tacrita0 what if you collapse the Favorites?

**Comment by tacrita0** [comment] 2019-10-30 06:16
> @tacrita0 what if you collapse the Favorites?

If the Favorite is collapsed, it's OK.
It would be great if it could work as before... I use Favorites to focus on a few folders.

**Comment by mihai-chezan** [comment] 2019-10-30 18:47
In that case, can't you collapse the other folders?
